### ISSUE TITLE
Set up branch protection rules for this repo

### ISSUE THREAD

**Issue by Peter9192** [esciencecenter-digital-skills/Lesson-FAIR-Data-Climate#10]
Right now, I can merge my own PR, without any approving reviews. It would be good to set up branch protection rules that prevent users from:
- pushing directly to master
- merging PRs that have not been approved by at least 1 reviewer

@mkuzak @SarahAlidoost I don't know who has access to these settings, but I'm sure I don't. Could one of you give it a try?

**Comment by SarahAlidoost** [comment]
I set this rule for the branch `gh-pages`:
```
Require pull request reviews before merging:
When enabled, all commits must be made to a non-protected branch and submitted via a pull request with the required number of approving reviews and no changes requested before it can be merged into a branch that matches this rule.
```

**Comment by Peter9192** [comment]
Now GH tells me a review is required for #9 :+1:
