### ISSUE TITLE
Add content to episode Conclusion

### ISSUE THREAD

**Issue by stefsmeets** [esciencecenter-digital-skills/Lesson-FAIR-Data-Climate#16]
Currently there is no content for the conclusion yet.

**Comment by Peter9192** [comment]
Some ideas that might be nice:
- Exercise using the entire FAIR data (go-fair) checklist to assess whether the chosen use case is FAIR, or which aspects can be improved (basically this should be combining the exercises from the previous episodes to make an overall 'verdict').
- A summary of how/why FAIR data is important and useful and the way to go
- Some links to good sources for further information
- A nice lookout of how FAIR data sits in the FAIR/open science landscape. Basically the same figure I added in the introduction (the turing way illustration).
- ...
