### ISSUE TITLE
Add solutions to exercises

### ISSUE THREAD

**Issue by sverhoeven** [esciencecenter-digital-skills/Lesson-FAIR-Data-Climate#37]
* The data access episode has `data repositories` exercise without a solution.
* The persistent identifiers episode is missing answers to the exercise questions.

An exercise should have a solution so participants know how well they did.

**Comment by rogerkuou** [comment]
I can work on these solutions and add them to those two episodes.

**Comment by rogerkuou** [comment]
@Peter9192 I will close this issue since the PR is merged.
