### ISSUE TITLE
Add content to episode Metadata

### ISSUE THREAD

**Issue by SarahAlidoost** [esciencecenter-digital-skills/Lesson-FAIR-Data-Climate#4]
The Metadata is still a rough outline, inspired by the what and why sections of https://www.howtofair.dk and other resources available in our collaboration document. It needs to be developed further.

**Comment by Peter9192** [comment]
A nice exercise would be to look up 'climate' on the [fairsharing website](https://fairsharing.org/standards/?q=climate), and then to find the conventions themselves ([here](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html)) and e.g. the [GMD paper](https://gmd.copernicus.org/articles/10/4619/2017/). This is what is used in EUCP. But there are other standards as well, e.g. the WMO standard.

**Comment by Peter9192** [comment]
Also note the CMIP5/6 ontologies/controlled vocabularies mentioned by V here: https://github.com/ESMValGroup/ESMValTool/issues/1825
